### ISSUE TITLE
i found a small bug on takser app 2.10

### ISSUE THREAD

**Issue by sarowarhosen03** [Learn-with-Sumit/rnext#1] opened 2024-01-10 20:05 UTC
here i notice that after the edit the task the taskToUpdate state isn't going back to default null value ,  
about detales video
[Kooha-2024-01-11-01-59-38.webm](https://github.com/Learn-with-Sumit/rnext/assets/98280301/7cab1099-8e3c-4a70-84c5-87b1bfa582d7)

how to reproduce
here after edit and save the task we need to 
in  src/task/TaskBoard.jsx
```
       setTaskToUpdate(null);
```
![image](https://github.com/Learn-with-Sumit/rnext/assets/98280301/fe02d548-4c7e-4a41-800d-06376d92bb3b)

**Comment by sarowarhosen03** [comment] 2024-01-10 20:09
if lws allow me to submit a pr i'm happy to do that

**Comment by atapas** [comment] 2024-01-11 05:56
@sarowarhosen03 vai,

The video is a bit unclear. But what I understood is..

- You edited a task..
- Then save it..
- Then you clicked on the Add Task button...

Here you do not find the modal fields blank but populated with the last edited task's details, right?

Yes! I can reproduce that. To take care of this case, we can simply call the function we have created for handling the close modal. It clears the edited task and also kill the modal. So you can call the `handleCloseClick();` function ay the end of `handleAddEditTask()` like this:

![image](https://github.com/Learn-with-Sumit/rnext/assets/3633137/871e1781-c936-4473-90b3-ad2df39c0138)

This way we do not have to maintain some code inside the else{} part and some outside. For Add task setting it to null is also fine.

I will commit the code changes. Thanks!

**Comment by sarowarhosen03** [comment] 2024-01-11 05:59
> @sarowarhosen03 vai,
> 
> The video is a bit unclear. But what I understood is..
> 
> - You edited a task..
> - Then save it..
> - Then you clicked on the Add Task button...
> 
> Here you do not find the modal fields blank but populated with the last edited task's details, right?
> 
> Yes! I can reproduce that. To take care of this case, we can simply call the function we have created for handling the close modal. It clears the edited task and also kill the modal. So you can call the `handleCloseClick();` function ay the end of `handleAddEditTask()` like this:
> 
> ![image](https://github.com/Learn-with-Sumit/rnext/assets/3633137/871e1781-c936-4473-90b3-ad2df39c0138)
> 
> This way we do not have to maintain some code inside the else{} part and some outside. For Add task setting it to null is also fine.
> 
> I will commit the code changes. Thanks!

Thanks sir.

**Comment by atapas** [comment] 2024-01-11 06:00
Closing it as the issue is addressed.

**Closed as completed by atapas** 2024-01-11 06:00 UTC
